---
- name: Play with dict
  hosts: localhost
  gather_facts: false
  vars:
    student_records: [{
      "first": "Praveen",
      "last": "Kumar",
      "mobile": "9958185454",
      "ctc": 100000,
      "address": {
        "city": "New Delhi",
        "country": "India"
      }
    },
    {
      "first": "Gyan",
      "last": "Jha",
      "mobile": "9958123456",
      "ctc": 150000,
      "address": {
        "city": "Noida",
        "country": "India"
      }
    },
    {
      "first": "Neeraj",
      "last": "Dixit",
      "mobile": "995818876",
      "ctc": 150000,
      "address": {
        "city": "Noida",
        "country": "India"
      }
    }]
    a: { "first": "Dhruv", "last": "Gupta", "mobile": "995816161", "ctc": 100000,  "address": {"city": "Noida", "country": "India" }}
    employees:
      {
        "praveen": {"mobile": "9958185454", "email": "praveen@gmail.com", "city": "New Delhi"},
        "ramesh": {"mobile": "9958186464", "email": "ramesh@gmail.com", "city": "New Delhi"},
        "devendra": {"mobile": "9958187575", "email": "devendra@gmail.com", "city": "Delhi"},
        "dhruv": {"mobile": "9958186161", "email": "dhruv@gmail.com", "city": "Noida"}
      }

  tasks:
    - name: Select and Extract only cities
      debug:
        msg: "{{ student_records | map(attribute='address') | map(attribute='city') | list }}"

    - name: Select and Extract only cities & country
      debug:
        msg: "{{ student_records | map(attribute='address') | list }}"

    - name: attribute joined with comma in single line
      debug:
        msg: "{{ student_records[item|int]['first'] + ',' + student_records[item|int]['last'] }}"
      loop: "{{ range((student_records|length)) | list }}"

    - name: attribute joined with comma in single line
      set_fact:
        firstlast: "{{ firstlast | default([]) + [student_records[item|int]['first'] + ',' + student_records[item|int]['last']] }}"
      loop: "{{ range((student_records|length)) | list }}"

    - debug: var=firstlast

    - name: Select only praveen's records
      debug:
        msg: "{{ ['praveen'] | map('extract', employees) | list }}"


    - name: Remove praveen's records
      debug:
        msg: "{{ student_records[item|int] | combine({'address': omit }) }}"
      loop: "{{ range(student_records|length) |list }}"


    - name: Add Dhruv's records
      set_fact:
        student_records: '{{ student_records | default({}) | combine(a) }}'
      # loop:
      #   - "{{ student_names }}"
      #   - "{{ a }}"

    # - debug: var=student_records

    # - name: Add dict
    #   debug:
    #     msg: |
    #       {% set _dummy = student_records.append(a) %}{{student_records}}

    - name: add new dict and set in variable
      set_fact:
        student_records: |
          {% set _dummy = student_records.append(a) %}
          {{student_records}}

    - debug: var=student_records
      
