---
- hosts: localhost
  gather_facts: false
  vars:
    data: "uswxapqzrtd563.uslttrr.amrs.bankofamerica.com,RHEL-8.6,HW-Dell,MODEL-PowerEdge-R740xd,CONSOLE-30.123.244.65,CONS_PING-Yes,USR-NA,PAS-NF,DRIVESTAT-Good,MEMSTAT-Good,PCISTAT-Good,DRIVEID-NA,,,RDST-NA,BIOSREL-12/13/2021,DATE-23-Nov-22,BATSTAT-,USBSTAT-Disabled"
    _regex: "(.*),(.*),HW-(.*),MODEL-(.*),CONSOLE-(.*),CONS_PING-(.*),USR-(.*),PAS-(.*),DRIVESTAT-(.*),MEMSTAT-(.*),PCISTAT-(.*),DRIVEID-(.*),,,RDST-(.*),BIOSREL-(.*),DATE-(.*),BATSTAT-(.*),USBSTAT-(.*)"
  tasks:

    - name: Capture Data using regex
      debug:
        msg:
          - "Hostname: {{ data | regex_replace(_regex, '\\1') }}"
          - "OS Version: {{ data | regex_replace(_regex, '\\2') }}"
          - "MODEL: {{ data | regex_replace(_regex, '\\3') }}"
          - "DRIVESTAT: {{ data | regex_replace(_regex, '\\9') }}"
